# -*- coding: utf-8 -*-
"""SentimentAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0hta7BkRn3CFTKd-zxKshJNzPrcS6YF

# **Sentiment Analysis - NLP Project**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("/content/twitter_validation.csv", encoding="ISO-8859-1", header=None)
# Assign column names
df.columns = ['Id', 'Social_media', 'target', 'text']
df

df.isna().sum()

df.dtypes

df['target'].value_counts()

# Visualization
sns.countplot(x=df['target'], data=df)

df.drop(df.index[(df['target'] == 'Irrelevant')], axis=0, inplace = True)
df

df.reset_index(drop=True, inplace=True)
df

df.drop(['Id', 'Social_media'], axis=1, inplace=True)
df

df['target']=df['target'].map({'Positive':1, 'Neutral':0, 'Negative': -1})
df

df.dtypes

tweets = df.text
tweets

# NLP (Natural Language Processing)
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Tokenization
from nltk.tokenize import TweetTokenizer
tk = TweetTokenizer()
tweets=tweets.apply(lambda x:tk.tokenize(x)).apply(lambda x: " ".join(x))
tweets

# Remove Special Characters
tweets = tweets.str.replace('[^A-Za-z0-9]+',' ')  #$$$$
tweets

from nltk.tokenize import word_tokenize
tweets = tweets.apply(lambda x: ' '.join([w for w in word_tokenize(x) if len(w)>3]))
tweets

# Stemming
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')
tweets = tweets.apply(lambda x: [stemmer.stem(i.lower()) for i in tk.tokenize(x)]).apply(lambda x: ' '.join(x))

# Stopwords Removing
from nltk.corpus import stopwords
sw = stopwords.words('english')
tweets = tweets.apply(lambda x: [i for i in tk.tokenize(x) if i not in sw]).apply(lambda x:' '.join(x))
tweets

# Vectorization - TF - IDF
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()
train_data = vec.fit_transform(tweets)
print(train_data.shape)

y = df['target'].values
y



x = train_data
x

from sklearn.model_selection import train_test_split

# Assuming x and y are defined
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

x_train

# Model Creation" KNN, Naive Bayes, SVC and DecisionTree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
knn = KNeighborsClassifier(n_neighbors=7)
model = BernoulliNB()
model1 = SVC()
model2 = DecisionTreeClassifier()
lst = [knn, model, model1, model2]

from sklearn.metrics import confusion_matrix, accuracy_score
for i in lst:
  print(i)
  i.fit(x_train, y_train)
  y_pred = i.predict(x_test)
  print(accuracy_score(y_test, y_pred))
  print(confusion_matrix(y_test, y_pred))

